/**
 * Application Error Codes
 * Matches backend ErrorCodes enum from DOCTOR_AND_PROVIDER_ADMIN_API.md
 */
export enum ErrorCode {
  // Authentication & Authorization
  INVALID_CLIENT = "INVALID_CLIENT",
  INVALID_GRANT = "INVALID_GRANT",
  INVALID_SCOPE = "INVALID_SCOPE",
  INVALID_TOKEN = "INVALID_TOKEN",
  TOKEN_EXPIRED = "TOKEN_EXPIRED",
  INVALID_IDENTITY = "INVALID_IDENTITY",
  INVALID_CREDENTIALS = "INVALID_CREDENTIALS",
  UNAUTHORIZED = "UNAUTHORIZED",
  FORBIDDEN = "FORBIDDEN",
  BRANCHE_ACCESS_DENIED = "BRANCHE_ACCESS_DENIED",
  DOCTOR_NOT_ASSOCIATED_WITH_BRANCH = "DOCTOR_NOT_ASSOCIATED_WITH_BRANCH",

  // User Errors
  USER_NOT_FOUND = "USER_NOT_FOUND",
  USER_EXISTS = "USER_EXISTS",
  USER_NOT_VERIFIED = "USER_NOT_VERIFIED",
  USER_BLOCKED = "USER_BLOCKED",
  USER_LOCKED = "USER_LOCKED",
  USER_SUSPENDED = "USER_SUSPENDED",
  USER_DISABLED = "USER_DISABLED",
  USER_IDENTITY_NOT_VERIFIED = "USER_IDENTITY_NOT_VERIFIED",
  USER_NOT_A_MEMBER_OF_A_FAMILY = "USER_NOT_A_MEMBER_OF_A_FAMILY",
  USER_IS_NOT_A_PRINCIPAL = "USER_IS_NOT_A_PRINCIPAL",
  USER_DOESNOT_HAVE_FAMILY_SUBSCRIPTION = "USER_DOESNOT_HAVE_FAMILY_SUBSCRIPTION",
  UNDER_15_YEARS = "UNDER_15_YEARS",

  // OTP Errors
  OTP_EXPIRED = "OTP_EXPIRED",
  OTP_NOT_FOUND = "OTP_NOT_FOUND",
  OTP_INVALID = "OTP_INVALID",
  OTP_LIMIT_EXCEEDED = "OTP_LIMIT_EXCEEDED",
  OTP_HOURLY_LIMIT_EXCEEDED = "OTP_HOURLY_LIMIT_EXCEEDED",
  OTP_RECENT_REQUEST = "OTP_RECENT_REQUEST",
  OTP_VERIFICATION_REQUIRED = "OTP_VERIFICATION_REQUIRED",

  // Mobile & Email Errors
  MOBILE_NOT_FOUND = "MOBILE_NOT_FOUND",
  MOBILE_ALREADY_EXISTS = "MOBILE_ALREADY_EXISTS",
  MOBILE_NOT_WHITELISTED = "MOBILE_NOT_WHITELISTED",
  EMAIL_ALREADY_EXIST = "EMAIL_ALREADY_EXIST",
  NATIONAL_ID_ALREADY_EXISTS = "NATIONAL_ID_ALREADY_EXISTS",
  PASSPORT_ID_ALREADY_EXISTS = "PASSPORT_ID_ALREADY_EXISTS",
  NID_DOB_INCONSISTENCY = "NID_DOB_INCONSISTENCY",

  // Resource Not Found
  NOT_FOUND = "NOT_FOUND",
  RESOURCE_NOT_FOUND = "RESOURCE_NOT_FOUND",
  ORDER_NOT_FOUND = "ORDER_NOT_FOUND",
  MEMBER_NOT_FOUND = "MEMBER_NOT_FOUND",
  ITEM_NOT_FOUND = "ITEM_NOT_FOUND",
  PROVIDER_NOT_FOUND = "PROVIDER_NOT_FOUND",
  BRANCH_NOT_FOUND = "BRANCH_NOT_FOUND",
  PLAN_NOT_FOUND = "PLAN_NOT_FOUND",
  CART_NOT_FOUND = "CART_NOT_FOUND",
  SPECIALITY_NOT_FOUND = "SPECIALITY_NOT_FOUND",
  GOVERNORATE_NOT_FOUND = "GOVERNORATE_NOT_FOUND",
  OFFER_NOT_FOUND = "OFFER_NOT_FOUND",
  MEDICAL_PROFILE_NOT_FOUND = "MEDICAL_PROFILE_NOT_FOUND",
  FAMILY_MEMBER_NOT_FOUND = "FAMILY_MEMBER_NOT_FOUND",
  PROMO_CODE_NOT_FOUND = "PROMO_CODE_NOT_FOUND",
  SERVICE_REQUEST_NOT_FOUND = "SERVICE_REQUEST_NOT_FOUND",
  CONSULTATION_NOT_FOUND = "CONSULTATION_NOT_FOUND",
  EMPLOYEE_NOT_FOUND = "EMPLOYEE_NOT_FOUND",

  // Order & Cart Errors
  ORDER_STATUS_NOT_ALLOWED = "ORDER_STATUS_NOT_ALLOWED",
  CART_ITEM_PRICE_MISMATCH = "CART_ITEM_PRICE_MISMATCH",
  INVALID_ACTION = "INVALID_ACTION",
  INVALID_TRANSACTION_TYPE = "INVALID_TRANSACTION_TYPE",

  // Promo Code Errors
  PROMO_CODE_NOT_ACTIVE = "PROMO_CODE_NOT_ACTIVE",
  PROMO_CODE_EXPIRED = "PROMO_CODE_EXPIRED",
  PROMO_CODE_ALREADY_USED = "PROMO_CODE_ALREADY_USED",
  PROMO_ALREADY_APPLIED = "PROMO_ALREADY_APPLIED",
  PROMO_NOT_APPLIED = "PROMO_NOT_APPLIED",

  // Balance & Points Errors
  INSUFFICIENT_BALANCE = "INSUFFICIENT_BALANCE",
  INSUFFICIENT_POINTS = "INSUFFICIENT_POINTS",
  INSUFFICIENT_BALANCE_TYPE = "INSUFFICIENT_BALANCE_TYPE",
  INVALID_AMOUNT = "INVALID_AMOUNT",
  INVALID_POINTS = "INVALID_POINTS",

  // File Errors
  INVALID_FILE = "INVALID_FILE",
  FILE_REQUIRED = "FILE_REQUIRED",
  INVALID_FILE_TYPE = "INVALID_FILE_TYPE",
  FILE_SIZE_TOO_LARGE = "FILE_SIZE_TOO_LARGE",
  FILE_NOT_PROVIDED = "FILE_NOT_PROVIDED",
  INVALID_FILE_CONTENT = "INVALID_FILE_CONTENT",
  TSV_PROCESSING_ERROR = "TSV_PROCESSING_ERROR",

  // Branch & Employee Errors
  MAX_EMPLOYEES_REACHED = "MAX_EMPLOYEES_REACHED",
  BRANCH_ALREADY_RATED = "BRANCH_ALREADY_RATED",
  DUPLICATE_RATING = "DUPLICATE_RATING",

  // Family Errors
  CANNOT_DELETE_PRINCIPAL = "CANNOT_DELETE_PRINCIPAL",
  FAMILY_MEMBER_UNAUTHORIZED = "FAMILY_MEMBER_UNAUTHORIZED",

  // Subscription Errors
  NO_ACTIVE_SUBSCRIPTION = "NO_ACTIVE_SUBSCRIPTION",
  ACTIVE_SUBSCRIPTION_EXISTS = "ACTIVE_SUBSCRIPTION_EXISTS",

  // Support Ticket
  TICKET_ALREADY_RESOLVED = "TICKET_ALREADY_RESOLVED",

  // Database Errors
  UNIQUE_VOILATION = "UNIQUE_VOILATION",
  FOREIGN_KEY_VIOLATION = "FOREIGN_KEY_VIOLATION",
  INVALID_FORMAT = "INVALID_FORMAT",
  NOT_NULL_CONSTRAINT = "NOT_NULL_CONSTRAINT",

  // Social Login
  SOCIAL_LOGIN_NO_PASSWORD = "SOCIAL_LOGIN_NO_PASSWORD",

  // Consultation Errors
  CONSULTATION_ALREADY_ASSIGNED = "CONSULTATION_ALREADY_ASSIGNED",
  SERVICE_REQUEST_ALREADY_ASSIGNED = "SERVICE_REQUEST_ALREADY_ASSIGNED",
  CANCELLATION_REASON_REQUIRED = "CANCELLATION_REASON_REQUIRED",

  // Miscellaneous
  INTERNAL_SERVER_ERROR = "INTERNAL_SERVER_ERROR",
  BAD_REQUEST = "BAD_REQUEST",
  METHOD_NOT_ALLOWED = "METHOD_NOT_ALLOWED",
  CONFLICT = "CONFLICT",
  INVALID_FILTERS = "INVALID_FILTERS",
  MAX_TRIALS_EXCEEDED = "MAX_TRIALS_EXCEEDED",
  MAX_USERS_REACHED = "MAX_USERS_REACHED",
}

export default ErrorCode;
